import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
       <div>
        <Link href="/">Home</Link>
        <Link href="/portfolio">Portfolio</Link>
       </div>
        {children}
      </body>
    </html>
  );
}
